tuplex=tuple("index tuple")
print(tuplex)
index=tuplex.index("p")
print(index)
index=tuplex.index("p",5)
print(index)
index=tuplex.index("e",3,6)
print(index)
#value error exception
index=tuplex.index("y")
print(index)
